"""added all tables

Revision ID: b5118bd05fa0
Revises: 72fb7301a163
Create Date: 2023-11-29 18:45:32.001812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5118bd05fa0'
down_revision: Union[str, None] = '72fb7301a163'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('age', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('weight', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('height', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('gender', sa.String(), nullable=True))
    op.add_column('users', sa.Column('activity_level', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_users_activity_level'), 'users', ['activity_level'], unique=False)
    op.create_index(op.f('ix_users_age'), 'users', ['age'], unique=False)
    op.create_index(op.f('ix_users_gender'), 'users', ['gender'], unique=False)
    op.create_index(op.f('ix_users_height'), 'users', ['height'], unique=False)
    op.create_index(op.f('ix_users_weight'), 'users', ['weight'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_weight'), table_name='users')
    op.drop_index(op.f('ix_users_height'), table_name='users')
    op.drop_index(op.f('ix_users_gender'), table_name='users')
    op.drop_index(op.f('ix_users_age'), table_name='users')
    op.drop_index(op.f('ix_users_activity_level'), table_name='users')
    op.drop_column('users', 'activity_level')
    op.drop_column('users', 'gender')
    op.drop_column('users', 'height')
    op.drop_column('users', 'weight')
    op.drop_column('users', 'age')
    # ### end Alembic commands ###
